import type { BgOverview } from "../../types/background";

export const mockBackgroundOverview: BgOverview = {
  generated_at: "2026-09-30T12:00:00.000Z",
  groups: [
    { id: "auto", title: "自动", hint: "定时与事件触发的管线" },
    { id: "on_demand", title: "按需", hint: "工具或界面触发" },
  ],
  lanes: [
    {
      id: "session_observe",
      group: "auto",
      title: "会话定稿观察",
      summary: "抽取记忆",
      cadence: "会话空闲 ≥ 24 小时后",
      worker: "derivation-worker",
      pause_key: "session_observe",
      steps: [
        { kind: "trigger", label: null, nodes: ["trigger.session_idle"] },
        {
          kind: "stage",
          label: null,
          nodes: ["memory.owner_extract", "code.lens_dispatch"],
        },
        { kind: "output", label: null, nodes: ["store.owner_memory"] },
      ],
    },
    {
      id: "card_maintenance",
      group: "auto",
      title: "卡片维护",
      summary: "整理与人设",
      cadence: "每 3600 秒检查各作用域",
      worker: "card-maintenance",
      pause_key: null,
      steps: [
        { kind: "trigger", label: null, nodes: ["trigger.card_tick"] },
        {
          kind: "stage",
          label: null,
          nodes: ["code.card_fade", "memory.owner_consolidate", "persona.evolve"],
        },
      ],
    },
    {
      id: "ondemand_archive",
      group: "on_demand",
      title: "会话归档",
      summary: "归档",
      cadence: "主对话调用归档工具时",
      worker: null,
      pause_key: null,
      steps: [
        { kind: "trigger", label: null, nodes: ["trigger.summarize"] },
        { kind: "stage", label: null, nodes: ["docs.archive"] },
        { kind: "output", label: null, nodes: ["store.kb_docs"] },
      ],
    },
  ],
  nodes: {
    "trigger.session_idle": {
      id: "trigger.session_idle",
      type: "trigger",
      title: "会话空闲",
      subtitle: "",
      trigger_kind: "schedule",
      description: "主人最后发言后空闲达到阈值。",
      conditions: [],
      limits: [],
      chain: null,
      temperature: null,
      purpose: null,
      prompts: [],
      guards: [],
      outputs: [],
      settings: ["memory_session_idle_hours"],
      constants: [],
      source_files: ["backend/app/main.py"],
      links: [],
      pause_key: null,
    },
    "memory.owner_extract": {
      id: "memory.owner_extract",
      type: "llm",
      title: "主人记忆抽取",
      subtitle: "辅助链 · T=0.1 · ≤8 条",
      trigger_kind: null,
      description: "从会话增量抽取主人画像。",
      conditions: ["会话未暂停抽取"],
      limits: ["每批最多 20 会话"],
      chain: "utility",
      temperature: 0.1,
      purpose: "memory.owner_extract",
      prompts: [
        {
          id: "default",
          label: "私聊",
          system: "你是抽取器。注入 {主人名}。",
          user_template: "会话内容：{transcript}",
          notes: [],
        },
        {
          id: "room",
          label: "群聊与互通",
          system: "你是抽取器（群聊）。",
          user_template: "房间 transcript",
          notes: ["多角色 lens"],
        },
      ],
      guards: ["三道门槛校验", "敏感门禁"],
      outputs: ["主人记忆条目"],
      settings: ["memory_session_idle_hours"],
      constants: [
        { label: "每会话上限", value: 8, source: "memory.MAX_FACTS" },
      ],
      source_files: ["backend/app/engine/memory/session_extractor.py"],
      links: [],
      pause_key: null,
    },
    "code.lens_dispatch": {
      id: "code.lens_dispatch",
      type: "code",
      title: "按会话分派",
      subtitle: "按通道与群聊选择 lens",
      trigger_kind: null,
      description: "按通道与群聊选择 lens。",
      conditions: [],
      limits: [],
      chain: null,
      temperature: null,
      purpose: null,
      prompts: [],
      guards: [],
      outputs: [],
      settings: [],
      constants: [],
      source_files: ["backend/app/engine/memory/worker.py"],
      links: [],
      pause_key: null,
    },
    "store.owner_memory": {
      id: "store.owner_memory",
      type: "store",
      title: "主人记忆库",
      subtitle: "",
      trigger_kind: null,
      description: "长期主人画像。",
      conditions: [],
      limits: [],
      chain: null,
      temperature: null,
      purpose: null,
      prompts: [],
      guards: [],
      outputs: ["主人记忆"],
      settings: [],
      constants: [],
      source_files: [],
      links: [],
      pause_key: null,
    },
    "trigger.card_tick": {
      id: "trigger.card_tick",
      type: "trigger",
      title: "定时检查",
      subtitle: "",
      trigger_kind: "schedule",
      description: "每小时维护线程。",
      conditions: [],
      limits: [],
      chain: null,
      temperature: null,
      purpose: null,
      prompts: [],
      guards: [],
      outputs: [],
      settings: [],
      constants: [],
      source_files: [],
      links: [],
      pause_key: null,
    },
    "code.card_fade": {
      id: "code.card_fade",
      type: "code",
      title: "卡片淡出",
      subtitle: "180 天无新出处 → 已淡出",
      trigger_kind: null,
      description: "无模型淡出规则。",
      conditions: [],
      limits: [],
      chain: null,
      temperature: null,
      purpose: null,
      prompts: [],
      guards: [],
      outputs: [],
      settings: [],
      constants: [],
      source_files: [],
      links: [],
      pause_key: null,
    },
    "memory.owner_consolidate": {
      id: "memory.owner_consolidate",
      type: "llm",
      title: "主人记忆整理",
      subtitle: "辅助链 · T=0.1",
      trigger_kind: null,
      description: "合并主人记忆。",
      conditions: [],
      limits: [],
      chain: "utility",
      temperature: 0.1,
      purpose: "memory.owner_consolidate",
      prompts: [],
      guards: [],
      outputs: [],
      settings: [],
      constants: [],
      source_files: [],
      links: [],
      pause_key: "consolidation",
    },
    "persona.evolve": {
      id: "persona.evolve",
      type: "llm",
      title: "人设进化",
      subtitle: "对话链 · T=0.1",
      trigger_kind: null,
      description: "修订人设。",
      conditions: [],
      limits: [],
      chain: "chat",
      temperature: 0.1,
      purpose: "persona.evolve",
      prompts: [],
      guards: [],
      outputs: [],
      settings: [],
      constants: [],
      source_files: [],
      links: [],
      pause_key: "persona_evolution",
    },
    "trigger.summarize": {
      id: "trigger.summarize",
      type: "trigger",
      title: "工具触发",
      subtitle: "",
      trigger_kind: "manual",
      description: "Agent 调用归档工具。",
      conditions: [],
      limits: [],
      chain: null,
      temperature: null,
      purpose: null,
      prompts: [],
      guards: [],
      outputs: [],
      settings: [],
      constants: [],
      source_files: [],
      links: [],
      pause_key: null,
    },
    "docs.archive": {
      id: "docs.archive",
      type: "llm",
      title: "归档合成",
      subtitle: "对话链",
      trigger_kind: null,
      description: "合成归档文档。",
      conditions: [],
      limits: [],
      chain: "chat",
      temperature: 0.2,
      purpose: "docs.archive",
      prompts: [
        {
          id: "default",
          label: "整段",
          system: "归档 system",
          user_template: "user",
          notes: [],
        },
      ],
      guards: [],
      outputs: ["知识库文档"],
      settings: ["summarize_segment_chars"],
      constants: [],
      source_files: [],
      links: [
        { lane: "session_observe", label: "落库后立即抽取" },
      ],
      pause_key: null,
    },
    "store.kb_docs": {
      id: "store.kb_docs",
      type: "store",
      title: "知识库",
      subtitle: "",
      trigger_kind: null,
      description: "写入 KB。",
      conditions: [],
      limits: [],
      chain: null,
      temperature: null,
      purpose: null,
      prompts: [],
      guards: [],
      outputs: [],
      settings: [],
      constants: [],
      source_files: [],
      links: [],
      pause_key: null,
    },
  },
  settings: {
    memory_session_idle_hours: {
      key: "memory_session_idle_hours",
      label: "会话空闲时长",
      kind: "number",
      value: 24,
      unit: "小时",
      min: 0.5,
      max: 168,
      step: 0.5,
      hint: "空闲后触发抽取",
    },
    summarize_segment_chars: {
      key: "summarize_segment_chars",
      label: "归档分段阈值",
      kind: "number",
      value: 28000,
      unit: "字",
      min: 4000,
      max: 200000,
      step: 1000,
      hint: "超出则分段",
    },
  },
  chains: {
    utility: {
      chain: "utility",
      label: "辅助链",
      models: [{ label: "主", model: "gpt-4o-mini" }],
    },
    chat: {
      chain: "chat",
      label: "对话链",
      models: [{ label: "主", model: "gpt-4o" }],
    },
    embed: {
      chain: "embed",
      label: "嵌入链",
      models: [{ label: "主", model: "text-embedding-3-small" }],
    },
  },
  pausable: [
    { key: "session_observe", label: "会话记忆抽取", hint: "" },
    { key: "consolidation", label: "整理", hint: "" },
    { key: "persona_evolution", label: "人设进化", hint: "" },
  ],
  status: {
    generated_at: "2026-09-30T12:00:00.000Z",
    paused: [],
    workers: {
      "derivation-worker": {
        name: "derivation-worker",
        label: "派生 worker",
        interval_seconds: 0.5,
        running: true,
        last_run_at: "2026-09-30T11:55:00.000Z",
        last_active_at: "2026-09-30T11:55:00.000Z",
        last_result: { session_observe: 1 },
        last_error: null,
        last_error_at: null,
      },
      "card-maintenance": {
        name: "card-maintenance",
        label: "卡片维护",
        interval_seconds: 3600,
        running: false,
        last_run_at: "2026-09-30T10:00:00.000Z",
        last_active_at: null,
        last_result: null,
        last_error: null,
        last_error_at: null,
      },
    },
    backlog: {
      session_observe_pending: 3,
      memory_dirty_conversations: 2,
      embed_pending: 10,
    },
    stats: {
      "memory.owner_extract": {
        calls_24h: 3,
        errors_24h: 0,
        calls_7d: 10,
        prompt_tokens_7d: 1000,
        completion_tokens_7d: 200,
        cost_7d: 0.05,
        last_call_at: "2026-09-30T11:00:00.000Z",
        last_status: "ok",
      },
    },
    totals_24h: {
      calls: 5,
      errors: 0,
      prompt_tokens: 1200,
      completion_tokens: 300,
      cost: 0.08,
    },
  },
};
