#!/usr/bin/env python3
"""Generate self-contained deploy/lorechat.sh and deploy/lorechat.ps1.

Sources:
  scripts/deploy-docker-compose.yml
  scripts/deploy.env.example
  docker/docker-compose.sandbox.yml  (SANDBOX_IMAGE default rewritten to GHCR)
  docker/opensandbox/config.toml     (execd / egress image pins)
  docker/docker-compose.sandbox.yml  (opensandbox/server image)

Also writes scripts/opensandbox-pins.sh for root lorechat-compose-lib.sh.

Usage (repo root):
  python3 scripts/gen-deploy-launchers.py
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
DEPLOY = ROOT / "deploy"
DOCKER = ROOT / "docker"
GHCR_SANDBOX = "ghcr.io/cnwinds/lore-chat-sandbox-agent:latest"


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def parse_opensandbox_pins() -> dict[str, str]:
    """Single source: config.toml + sandbox compose server image line."""
    config = read(DOCKER / "opensandbox" / "config.toml")
    sandbox_yml = read(DOCKER / "docker-compose.sandbox.yml")

    execd = re.search(r'(?m)^execd_image\s*=\s*"([^"]+)"', config)
    egress = re.search(r'(?m)^\[egress\]\s*\n(?:.*\n)*?image\s*=\s*"([^"]+)"', config)
    if not egress:
        # simpler: first image = after [egress]
        egress = re.search(
            r"(?ms)^\[egress\].*?^image\s*=\s*\"([^\"]+)\"",
            config,
        )
    server = re.search(
        r"(?m)^\s+image:\s*(opensandbox/server:\S+)\s*$",
        sandbox_yml,
    )
    if not execd or not egress or not server:
        raise SystemExit(
            "failed to parse opensandbox pins from config.toml / docker-compose.sandbox.yml"
        )
    return {
        "server": server.group(1),
        "execd": execd.group(1),
        "egress": egress.group(1),
    }


def write_pins_sh(pins: dict[str, str]) -> None:
    path = SCRIPTS / "opensandbox-pins.sh"
    path.write_text(
        f"""# Generated by scripts/gen-deploy-launchers.py — do not hand-edit.
# Source of truth: docker/opensandbox/config.toml + docker/docker-compose.sandbox.yml
LORECHAT_OPENSANDBOX_SERVER_IMAGE="${{LORECHAT_OPENSANDBOX_SERVER_IMAGE:-{pins["server"]}}}"
LORECHAT_OPENSANDBOX_EXECD_IMAGE="${{LORECHAT_OPENSANDBOX_EXECD_IMAGE:-{pins["execd"]}}}"
LORECHAT_OPENSANDBOX_EGRESS_IMAGE="${{LORECHAT_OPENSANDBOX_EGRESS_IMAGE:-{pins["egress"]}}}"
""",
        encoding="utf-8",
    )


def sandbox_for_deploy(src: str) -> str:
    old = "SANDBOX_IMAGE: ${SANDBOX_IMAGE:-lorechat-sandbox-agent:local}"
    new = f"SANDBOX_IMAGE: ${{SANDBOX_IMAGE:-{GHCR_SANDBOX}}}"
    if old not in src:
        raise SystemExit(
            "docker/docker-compose.sandbox.yml: expected local SANDBOX_IMAGE default not found"
        )
    body = src.replace(old, new)
    header = (
        "# Work overlay for prebuilt images "
        f"(default SANDBOX_IMAGE={GHCR_SANDBOX}).\n"
        "# Embedded by gen-deploy-launchers.py from docker/docker-compose.sandbox.yml.\n"
    )
    return header + body


def bash_heredoc(rel: str, content: str) -> str:
    return (
        f'  write_file "${{ROOT}}/{rel}" <<\'LORECHAT_EOF\'\n'
        f"{content.rstrip()}\n"
        "LORECHAT_EOF\n"
    )


def ps_here_string(rel: str, content: str) -> str:
    safe = content.replace("\r\n", "\n").rstrip() + "\n"
    if "\n'@\n" in f"\n{safe}":
        raise SystemExit(f"{rel}: content contains PowerShell here-string terminator")
    return f"  Write-BundleFile '{rel}' @'\n{safe}'@\n"


def build_bash(
    compose: str,
    sandbox: str,
    config: str,
    env_example: str,
    pins: dict[str, str],
) -> str:
    assets = "".join(
        [
            bash_heredoc("docker-compose.yml", compose),
            bash_heredoc("docker-compose.sandbox.yml", sandbox),
            bash_heredoc("opensandbox/config.toml", config),
            bash_heredoc(".env.example", env_example),
        ]
    )
    return f'''#!/usr/bin/env bash
# Lore Chat 单文件启动器（Linux / macOS）
# 用法: ./lorechat.sh start [--chat|--work]
# 自包含：运行时在脚本旁写出 compose / 沙箱配置，无需仓库其它文件。
# 生成: python3 scripts/gen-deploy-launchers.py
set -euo pipefail

ROOT="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
RUNTIME="${{ROOT}}/.lorechat"
MODE_FILE="${{RUNTIME}}/run-mode"
DEFAULT_SANDBOX_IMAGE="{GHCR_SANDBOX}"
OPENSANDBOX_SERVER_IMAGE="{pins["server"]}"
OPENSANDBOX_EXECD_IMAGE="{pins["execd"]}"
OPENSANDBOX_EGRESS_IMAGE="{pins["egress"]}"

usage() {{
  cat <<'EOF'
Usage: ./lorechat.sh <command> [options]

Commands:
  start [--chat|--work]   启动（可每次选择聊天 / Work 模式）
  stop                    停止
  update [--chat|--work]  拉取最新镜像并启动
  prepare                 仅写出 compose / 配置（不启动）
  log|logs                查看日志
  help                    帮助

Modes:
  --chat   仅对话与知识库
  --work   带 OpenSandbox（首次镜像较大时会提示）
EOF
}}

need_cmd() {{
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "[Lore Chat] 缺少命令: $1（请先安装 Docker）" >&2
    exit 1
  fi
}}

write_file() {{
  local path="$1"
  mkdir -p "$(dirname "${{path}}")"
  cat >"${{path}}"
}}

materialize_bundle() {{
  mkdir -p "${{ROOT}}/opensandbox" "${{ROOT}}/data/knowledge" "${{ROOT}}/data/backups" "${{RUNTIME}}"
{assets}
  if [[ ! -f "${{ROOT}}/.env" ]]; then
    cp "${{ROOT}}/.env.example" "${{ROOT}}/.env"
    echo "[Lore Chat] 已创建 .env（API Key 可在网页设置中填写）"
  fi
}}

read_saved_mode() {{
  if [[ -f "${{MODE_FILE}}" ]]; then
    tr -d '[:space:]' <"${{MODE_FILE}}"
  else
    echo "chat"
  fi
}}

save_mode() {{
  mkdir -p "${{RUNTIME}}"
  printf '%s\\n' "$1" >"${{MODE_FILE}}"
}}

pick_mode_interactive() {{
  local saved default_idx=1 choice
  saved="$(read_saved_mode)"
  [[ "${{saved}}" == "work" ]] && default_idx=2
  echo "[Lore Chat] 请选择启动模式："
  echo "  1) 聊天模式 — 对话与知识库（默认更轻量）"
  echo "  2) Work 模式 — 额外启用沙箱执行（首次镜像较大）"
  read -r -p "输入 1 或 2 [默认 ${{default_idx}}]: " choice || true
  choice="${{choice:-${{default_idx}}}}"
  case "${{choice}}" in
    2|work|WORK) echo "work" ;;
    *) echo "chat" ;;
  esac
}}

resolve_mode() {{
  local flag="${{1:-}}"
  case "${{flag}}" in
    --chat|chat) echo "chat" ;;
    --work|work) echo "work" ;;
    "")
      if [[ -t 0 ]]; then
        pick_mode_interactive
      else
        read_saved_mode
      fi
      ;;
    *)
      echo "[Lore Chat] 未知模式: ${{flag}}（用 --chat 或 --work）" >&2
      return 1
      ;;
  esac
}}

sandbox_image_ref() {{
  local from_env=""
  if [[ -f "${{ROOT}}/.env" ]]; then
    from_env="$(grep -E '^SANDBOX_IMAGE=' "${{ROOT}}/.env" 2>/dev/null | cut -d= -f2- | tr -d '\\r' || true)"
  fi
  echo "${{from_env:-${{SANDBOX_IMAGE:-${{DEFAULT_SANDBOX_IMAGE}}}}}}"
}}

image_present() {{
  docker image inspect "$1" >/dev/null 2>&1
}}

work_images_cached() {{
  local agent
  agent="$(sandbox_image_ref)"
  image_present "${{OPENSANDBOX_SERVER_IMAGE}}" \\
    && image_present "${{agent}}" \\
    && image_present "${{OPENSANDBOX_EXECD_IMAGE}}" \\
    && image_present "${{OPENSANDBOX_EGRESS_IMAGE}}"
}}

warn_work_images() {{
  if work_images_cached; then
    echo "[Lore Chat] Work 模式：本机已有沙箱相关镜像，将按需检查更新。"
    return
  fi
  echo "[Lore Chat] Work 模式将额外拉取沙箱相关镜像（opensandbox/server、execd、egress、sandbox-agent 等）。"
  echo "[Lore Chat] 首次下载可能较慢，请耐心等待。"
}}

run_compose() {{
  local mode="$1"
  shift
  need_cmd docker
  if ! docker compose version >/dev/null 2>&1; then
    echo "[Lore Chat] 需要 Docker Compose 插件（docker compose）" >&2
    exit 1
  fi
  local -a files=(-f "${{ROOT}}/docker-compose.yml")
  if [[ "${{mode}}" == "work" ]]; then
    files+=(-f "${{ROOT}}/docker-compose.sandbox.yml")
  fi
  docker compose --project-directory "${{ROOT}}" --env-file "${{ROOT}}/.env" "${{files[@]}}" "$@"
}}

teardown_all() {{
  run_compose work down --remove-orphans >/dev/null 2>&1 || true
  run_compose chat down --remove-orphans >/dev/null 2>&1 || true
}}

web_port() {{
  local port
  port="$(grep -E '^WEB_PORT=' "${{ROOT}}/.env" 2>/dev/null | cut -d= -f2- | tr -d '\\r' || true)"
  echo "${{port:-8080}}"
}}

do_start() {{
  materialize_bundle
  local mode
  mode="$(resolve_mode "${{1:-}}")" || exit 1
  if [[ "${{mode}}" == "work" ]]; then
    warn_work_images
  fi
  echo "[Lore Chat] 正在启动（模式: ${{mode}}）..."
  teardown_all
  run_compose "${{mode}}" pull
  run_compose "${{mode}}" up -d
  save_mode "${{mode}}"
  echo "[Lore Chat] 就绪 → http://localhost:$(web_port)"
  echo "[Lore Chat] 模式 → ${{mode}}；日志 → ./lorechat.sh log"
  echo "[Lore Chat] 若尚未配置 API Key，打开页面后会引导填写。"
}}

do_stop() {{
  materialize_bundle
  teardown_all
  echo "[Lore Chat] 已停止"
}}

do_update() {{
  local mode
  if [[ -n "${{1:-}}" ]]; then
    mode="$(resolve_mode "$1")" || exit 1
  else
    mode="$(read_saved_mode)"
  fi
  do_start "${{mode}}"
}}

do_log() {{
  materialize_bundle
  run_compose "$(read_saved_mode)" logs -f --tail=50
}}

do_prepare() {{
  materialize_bundle
  echo "[Lore Chat] 已写出 docker-compose.yml / sandbox / opensandbox/config.toml / .env.example"
  echo "[Lore Chat] 目录: ${{ROOT}}"
}}

cmd="${{1:-help}}"
shift || true
case "${{cmd}}" in
  start) do_start "${{1:-}}" ;;
  stop) do_stop ;;
  update) do_update "${{1:-}}" ;;
  prepare) do_prepare ;;
  log|logs) do_log ;;
  help|-h|--help) usage ;;
  *)
    usage >&2
    exit 1
    ;;
esac
'''


def build_ps1(
    compose: str,
    sandbox: str,
    config: str,
    env_example: str,
    pins: dict[str, str],
) -> str:
    assets = "".join(
        [
            ps_here_string("docker-compose.yml", compose),
            ps_here_string("docker-compose.sandbox.yml", sandbox),
            ps_here_string("opensandbox/config.toml", config),
            ps_here_string(".env.example", env_example),
        ]
    )
    return f'''# Lore Chat 单文件启动器（Windows PowerShell）
# 用法: .\\lorechat.ps1 start [--chat|--work]
# 自包含：运行时在脚本旁写出 compose / 沙箱配置。
# 生成: python3 scripts/gen-deploy-launchers.py
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$Runtime = Join-Path $Root ".lorechat"
$ModeFile = Join-Path $Runtime "run-mode"
$DefaultSandboxImage = "{GHCR_SANDBOX}"
$OpensandboxServerImage = "{pins["server"]}"
$OpensandboxExecdImage = "{pins["execd"]}"
$OpensandboxEgressImage = "{pins["egress"]}"

function Show-Usage {{
  @"
Usage: .\\lorechat.ps1 <command> [options]

Commands:
  start [--chat|--work]   Start (chat or Work mode)
  stop                    Stop
  update [--chat|--work]  Pull images and start
  prepare                 Write compose/config only
  log                     Tail logs
  help                    Help
"@
}}

function Write-BundleFile([string]$RelPath, [string]$Content) {{
  $path = Join-Path $Root $RelPath
  $dir = Split-Path -Parent $path
  if ($dir) {{ New-Item -ItemType Directory -Force -Path $dir | Out-Null }}
  $utf8 = New-Object System.Text.UTF8Encoding $false
  [System.IO.File]::WriteAllText($path, $Content.TrimEnd() + "`n", $utf8)
}}

function Materialize-Bundle {{
  New-Item -ItemType Directory -Force -Path $Runtime | Out-Null
  New-Item -ItemType Directory -Force -Path (Join-Path $Root "data\\knowledge") | Out-Null
  New-Item -ItemType Directory -Force -Path (Join-Path $Root "data\\backups") | Out-Null
{assets}
  $envPath = Join-Path $Root ".env"
  $example = Join-Path $Root ".env.example"
  if (-not (Test-Path $envPath)) {{
    Copy-Item $example $envPath
    Write-Host "[Lore Chat] Created .env (set API Key in the web UI if needed)"
  }}
}}

function Read-SavedMode {{
  if (Test-Path $ModeFile) {{ return ((Get-Content $ModeFile -Raw).Trim()) }}
  return "chat"
}}

function Save-Mode([string]$Mode) {{
  New-Item -ItemType Directory -Force -Path $Runtime | Out-Null
  Set-Content -Path $ModeFile -Value $Mode -NoNewline
}}

function Test-CanPrompt {{
  if (-not [Environment]::UserInteractive) {{ return $false }}
  try {{ if ([Console]::IsInputRedirected) {{ return $false }} }} catch {{ return $false }}
  return $true
}}

function Resolve-Mode([string]$Flag) {{
  switch -Regex ($Flag) {{
    "^(--chat|chat)$" {{ return "chat" }}
    "^(--work|work)$" {{ return "work" }}
    "^$" {{
      if (-not (Test-CanPrompt)) {{ return (Read-SavedMode) }}
      $saved = Read-SavedMode
      $default = if ($saved -eq "work") {{ "2" }} else {{ "1" }}
      Write-Host "[Lore Chat] Choose mode:"
      Write-Host "  1) Chat — knowledge base conversation"
      Write-Host "  2) Work — plus sandbox execution"
      $choice = Read-Host "Enter 1 or 2 [default $default]"
      if ([string]::IsNullOrWhiteSpace($choice)) {{ $choice = $default }}
      if ($choice -eq "2") {{ return "work" }}
      return "chat"
    }}
    default {{ throw "Unknown mode: $Flag (use --chat or --work)" }}
  }}
}}

function Get-SandboxImageRef {{
  $envPath = Join-Path $Root ".env"
  if (Test-Path $envPath) {{
    $line = Get-Content $envPath | Where-Object {{ $_ -match "^SANDBOX_IMAGE=" }} | Select-Object -First 1
    if ($line) {{
      $val = ($line -split "=", 2)[1].Trim()
      if ($val) {{ return $val }}
    }}
  }}
  if ($env:SANDBOX_IMAGE) {{ return $env:SANDBOX_IMAGE }}
  return $DefaultSandboxImage
}}

function Test-DockerImage([string]$Image) {{
  docker image inspect $Image 2>$null | Out-Null
  return ($LASTEXITCODE -eq 0)
}}

function Test-WorkImagesCached {{
  $agent = Get-SandboxImageRef
  return (Test-DockerImage $OpensandboxServerImage) `
    -and (Test-DockerImage $agent) `
    -and (Test-DockerImage $OpensandboxExecdImage) `
    -and (Test-DockerImage $OpensandboxEgressImage)
}}

function Warn-WorkImages {{
  if (Test-WorkImagesCached) {{
    Write-Host "[Lore Chat] Work mode: sandbox images already present; will check for updates."
    return
  }}
  Write-Host "[Lore Chat] Work mode will pull extra sandbox images (server, execd, egress, sandbox-agent)."
  Write-Host "[Lore Chat] First download may take a while."
}}

function Get-ComposeArgs([string]$Mode) {{
  $a = @("--project-directory", $Root, "--env-file", (Join-Path $Root ".env"), "-f", (Join-Path $Root "docker-compose.yml"))
  if ($Mode -eq "work") {{
    $a += @("-f", (Join-Path $Root "docker-compose.sandbox.yml"))
  }}
  return $a
}}

function Invoke-Compose([string]$Mode, [string[]]$ComposeCommand) {{
  if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {{
    throw "Docker not found. Install Docker Desktop first."
  }}
  $a = (Get-ComposeArgs $Mode) + $ComposeCommand
  & docker compose @a
  if ($LASTEXITCODE -ne 0) {{ throw "docker compose failed ($LASTEXITCODE)" }}
}}

function Teardown-All {{
  try {{ Invoke-Compose "work" @("down", "--remove-orphans") | Out-Null }} catch {{ }}
  try {{ Invoke-Compose "chat" @("down", "--remove-orphans") | Out-Null }} catch {{ }}
}}

function Get-WebPort {{
  $envPath = Join-Path $Root ".env"
  $line = Get-Content $envPath | Where-Object {{ $_ -match "^WEB_PORT=" }} | Select-Object -First 1
  if ($line) {{ return ($line -split "=", 2)[1].Trim() }}
  return "8080"
}}

function Start-Lore([string]$Flag) {{
  Materialize-Bundle
  $mode = Resolve-Mode $Flag
  if ($mode -eq "work") {{ Warn-WorkImages }}
  Write-Host "[Lore Chat] Starting (mode: $mode)..."
  Teardown-All
  Invoke-Compose $mode @("pull")
  Invoke-Compose $mode @("up", "-d")
  Save-Mode $mode
  $port = Get-WebPort
  Write-Host "[Lore Chat] Ready -> http://localhost:$port"
  Write-Host "[Lore Chat] Mode -> $mode; logs -> .\\lorechat.ps1 log"
  Write-Host "[Lore Chat] If API Key is missing, the web UI will guide you."
}}

$cmd = if ($args.Count -ge 1) {{ $args[0] }} else {{ "help" }}
$opt = if ($args.Count -ge 2) {{ $args[1] }} else {{ "" }}

switch ($cmd) {{
  "start" {{ Start-Lore $opt }}
  "stop" {{
    Materialize-Bundle
    Teardown-All
    Write-Host "[Lore Chat] Stopped"
  }}
  "update" {{
    if ($opt) {{ Start-Lore $opt }} else {{ Start-Lore (Read-SavedMode) }}
  }}
  "prepare" {{
    Materialize-Bundle
    Write-Host "[Lore Chat] Wrote compose / sandbox / opensandbox/config.toml / .env.example"
    Write-Host "[Lore Chat] Dir: $Root"
  }}
  "log" {{ Materialize-Bundle; Invoke-Compose (Read-SavedMode) @("logs", "-f", "--tail=50") }}
  "logs" {{ Materialize-Bundle; Invoke-Compose (Read-SavedMode) @("logs", "-f", "--tail=50") }}
  "help" {{ Show-Usage }}
  "-h" {{ Show-Usage }}
  "--help" {{ Show-Usage }}
  default {{
    Show-Usage
    exit 1
  }}
}}
'''


def main() -> None:
    pins = parse_opensandbox_pins()
    write_pins_sh(pins)

    compose = read(SCRIPTS / "deploy-docker-compose.yml")
    env_example = read(SCRIPTS / "deploy.env.example")
    sandbox = sandbox_for_deploy(read(DOCKER / "docker-compose.sandbox.yml"))
    config = read(DOCKER / "opensandbox" / "config.toml")

    DEPLOY.mkdir(parents=True, exist_ok=True)
    sh_path = DEPLOY / "lorechat.sh"
    ps_path = DEPLOY / "lorechat.ps1"
    sh_path.write_text(build_bash(compose, sandbox, config, env_example, pins), encoding="utf-8")
    sh_path.chmod(sh_path.stat().st_mode | 0o111)
    ps_path.write_text(build_ps1(compose, sandbox, config, env_example, pins), encoding="utf-8")
    print(f"pins: server={pins['server']} execd={pins['execd']} egress={pins['egress']}")
    print(f"wrote {SCRIPTS.relative_to(ROOT)}/opensandbox-pins.sh")
    print(f"wrote {sh_path.relative_to(ROOT)} ({sh_path.stat().st_size} bytes)")
    print(f"wrote {ps_path.relative_to(ROOT)} ({ps_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
