# Generated by scripts/gen-deploy-launchers.py — do not hand-edit.
# Source of truth: docker/opensandbox/config.toml + docker/docker-compose.sandbox.yml
LORECHAT_OPENSANDBOX_SERVER_IMAGE="${LORECHAT_OPENSANDBOX_SERVER_IMAGE:-opensandbox/server:latest}"
LORECHAT_OPENSANDBOX_EXECD_IMAGE="${LORECHAT_OPENSANDBOX_EXECD_IMAGE:-opensandbox/execd:v1.0.18}"
LORECHAT_OPENSANDBOX_EGRESS_IMAGE="${LORECHAT_OPENSANDBOX_EGRESS_IMAGE:-opensandbox/egress:v1.1.0}"
